In [7]:
import numpy as np

## Numpy Array

In [11]:
myList = [20,30,40]
myList

[20, 30, 40]

In [9]:
np.array(myList)

array([20, 30, 40])

In [13]:
matrixList = [[10,20,30],[40,50,60],[70,80,90]]

In [15]:
matrixList

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [17]:
np.array(matrixList)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

## arange

In [28]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## zeros

In [31]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [33]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

## ones

In [40]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## linspace

In [45]:
np.linspace(0,20,7)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        ])

## eye

In [48]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random

In [53]:
np.random.randn(8)

array([-0.12598917, -0.02454166, -0.68758646, -0.5165438 , -0.25333339,
       -1.78182006, -0.10316757,  0.2334815 ])

In [55]:
np.random.randn(8,8)

array([[ 1.88872143, -0.84933618,  0.13692407, -0.41107529, -0.94576167,
         0.73670872, -0.17311055, -0.25780056],
       [ 0.14517097,  0.62793143,  0.30581351, -0.5929037 ,  0.59586588,
        -0.83830056,  0.05224281, -0.09020053],
       [-0.6607916 ,  0.22378652, -0.32676767, -0.19470658,  1.06908213,
        -0.71362071,  0.7239447 ,  1.00944711],
       [ 0.0864091 ,  0.07018806, -1.45459472,  0.67347619,  0.36086345,
         0.5198454 , -0.37628785, -1.85541859],
       [ 0.45613101,  1.56307308,  0.09907344,  0.2518004 ,  0.50463217,
        -2.51194184,  1.22087788, -0.57136333],
       [ 0.60337455,  0.58756118,  0.68324037, -0.53852689, -0.36922616,
        -0.55400694,  1.3139732 , -0.47124832],
       [ 0.11674608, -0.56449766, -0.72005844, -0.98364208,  0.51704336,
        -1.29303955, -0.97833762,  0.54693432],
       [-0.14830176,  0.38908031,  0.78307809, -1.492911  , -0.35831239,
         0.7062443 , -1.48432365, -1.03703055]])

In [63]:
np.random.randint(1,10)

7

In [65]:
np.random.randint(1,10,5)

array([8, 8, 7, 8, 3])

## NumPy Array Methods

In [70]:
myRandomArray = np.random.randint(1,100,20)
myRandomArray

array([72, 90, 38, 72, 35, 56, 56, 59,  3, 48, 97, 13, 95, 94, 28, 55, 75,
       42, 75, 19])

In [72]:
myRandomArray.reshape(5,4) # convert to matrix

array([[72, 90, 38, 72],
       [35, 56, 56, 59],
       [ 3, 48, 97, 13],
       [95, 94, 28, 55],
       [75, 42, 75, 19]])

In [74]:
myRandomArray.max()

97

In [76]:
myRandomArray.min()

3

In [78]:
myRandomArray.argmax()

10

In [80]:
myRandomArray.argmin()

8

In [84]:
newArray = np.arange(0,15,1)
newArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [86]:
newArray[0:5]

array([0, 1, 2, 3, 4])

In [88]:
newArray[3:7]

array([3, 4, 5, 6])

## Matrix

In [11]:
exampleArray = np.arange(1,20,2)

exampleArray

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [13]:
exampleMatrix = exampleArray.reshape(5,2)

In [15]:
exampleMatrix

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [17]:
exampleMatrix[1][1]

7

In [21]:
exampleMatrix[1:,1:]

array([[ 7],
       [11],
       [15],
       [19]])

## Operations

In [28]:
newArr = np.random.randint(1,100,20)

In [30]:
newArr

array([12,  7, 48, 97, 72, 41,  6, 65, 46, 60, 96, 88, 65, 57, 73, 37, 95,
       19, 64, 53])

In [32]:
newArr > 23

array([False, False,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True])

In [34]:
np.sqrt(newArr)

array([3.46410162, 2.64575131, 6.92820323, 9.8488578 , 8.48528137,
       6.40312424, 2.44948974, 8.06225775, 6.78232998, 7.74596669,
       9.79795897, 9.38083152, 8.06225775, 7.54983444, 8.54400375,
       6.08276253, 9.74679434, 4.35889894, 8.        , 7.28010989])

In [38]:
np.average(newArr)

55.05